package main

// defaultClubAcronyms contains 1969 club name to acronym mappings.
// Generated from frontend/src/themes.js CLUB_ACRONYMS.
var defaultClubAcronyms = map[string]string{
	"Abbey Runners": "ABRUN",
	"Aberdare Valley AAC": "ABERV",
	"Aberdeen Amateur Athletic Club": "ABERD",
	"Aberdeen University AC": "UABER",
	"Abergele Harriers": "ABRGH",
	"Abertay University": "ABRTU",
	"Aberystwyth AC": "ABERY",
	"Abingdon Amblers AC": "ABIAM",
	"Abingdon Athletics Club": "ABN",
	"Absolute Tri": "ABTRI",
	"Academi Coed y Brenin": "ACYB",
	"Accrington Road Runners": "ACTRR",
	"Achilles Club": "ACH",
	"Ackworth Road Runners": "ACKRR",
	"Acorns AC": "ACORN",
	"Active Soul UK": "ASOUL",
	"Active Training World RC": "ATWRC",
	"AD Marathon": "ADMAR",
	"Advent Runners": "ADV",
	"AECC University College": "AECC",
	"Agile Therapy Run": "AGILE",
	"Air Products Flyers": "APF",
	"Airdrie Harriers": "AIRDR",
	"Airecentre Pacers RC": "ACPRC",
	"Albany Road Run Club": "ARRC",
	"Albertville Harriers": "ALBRT",
	"Alchester Running Club": "ALCH",
	"Aldershot Farnham & District": "AFD",
	"Aldridge Running Club": "ALDRC",
	"All Stars Special Olympics Club": "ALLST",
	"Allerton Junior Athletics Club": "ALTNJ",
	"Almost Athletes": "ALMAT",
	"Alnwick Harriers": "ALNWH",
	"Alton Runners": "ALTON",
	"Altrincham & District Athletic Club Limited": "ALTRD",
	"Amazing Feet Running Club": "AMFRC",
	"Amber Valley and Erewash Athletic Club": "AMBER",
	"Ambleside AC": "AMBLA",
	"Amman Valley Harriers": "AMMAN",
	"Ampthill & Flitwick Flyers RC": "AFF",
	"Andover AC": "ANDAC",
	"Angels RC": "ANGEL",
	"Annadale Striders": "ANNAD",
	"Annan and District Athletics Club": "ANNAN",
	"Anster Haddies Running Club": "ANSTH",
	"Arbroath & District Athletics Club": "ARBRD",
	"Arbroath Footers Running Club": "ARBRF",
	"Arcus": "ARCUS",
	"Arena 80 AC": "ARE80",
	"ARK Sport": "ARK",
	"Armagh Athletic Club Armagh AC": "ARMAG",
	"Arran Runners": "ARRAN",
	"Arunners RC": "ARU",
	"Ashbourne Running Club": "ASHRC",
	"Ashford & District RRC": "ASHFD",
	"Ashford AC": "ASHFA",
	"Ashford Striders RC": "ASHST",
	"Ashington Hirst Running Club": "AHRC",
	"Ashton Keynes Running Club": "AKRC",
	"Askern District RC": "ASKD",
	"Astley & Tyldesley Road Runners": "ATRR",
	"Aston University AC": "ASTON",
	"Athletics Northern Ireland": "ANI",
	"AthleticsNI Unattached": "ANIUN",
	"Atlas Running Club": "ATLAS",
	"Attleborough Athletics Academy": "ATTLE",
	"Aurora Harriers": "AURH",
	"Australian Masters Team": "XXAUS",
	"Avon Valley Runners": "AVONV",
	"Axe Valley Runners": "AXEVR",
	"Aycliffe Running Club": "AYCL",
	"Aylsham Runners": "ASHAM",
	"Ayr Seaforth AC": "AYRS",
	"Ayrodynamic Triathlon Club": "AYROT",
	"Ayrshire Harriers Clubs Association": "AHCA",
	"Bad Boy Running Club": "BBRC",
	"Badgers": "BADGE",
	"Badminton England": "BE",
	"Badu Sports": "BADU",
	"Baildon Runners": "BAILR",
	"Ballycastle Runners AC": "BCAST",
	"Ballydrain Harriers AC": "BDRAI",
	"Ballyfin AC": "BFIN",
	"Ballygalget AC": "BGGT",
	"Ballymena and Antrim AC": "BAAC",
	"Ballymena Runners AC": "BALLY",
	"Balsall Common Run Club": "BALSA",
	"Banbridge AC": "BANB",
	"Banbury Harriers Athletics Club": "BANBH",
	"Banchory Stonehaven Athletics Club": "BSAC",
	"Bangor University AC": "UBANG",
	"Bannister Athletic Club": "BANAC",
	"Barclays Running Club": "BARC",
	"Barking Road Runners": "BRKRR",
	"Barlestone St Giles RC": "BSGRC",
	"Barlick Fell Runners": "BARLF",
	"Barnes Runners": "BAR",
	"Barnet & District AC": "BARN",
	"Barnsley Athletic Club": "BARNS",
	"Barnsley Harriers": "BARNH",
	"Barrow & Furness Striders AC": "BARFS",
	"Barrow Runners": "BARWR",
	"Barry & Vale Harriers": "BARR",
	"Barton & District AC": "BARAC",
	"Barts and the London AC": "BARTS",
	"Basildon AC": "BAS",
	"Basildon Beagles": "BASB",
	"Basingstoke & Mid Hants AC": "BMH",
	"Bath Amphibians": "BATHA",
	"Be Fit Today Track Academy": "BFTA",
	"Bearbrook Running Club": "BBR",
	"Beaumont RC": "BEAU",
	"Beccles & Bungay Harriers": "BECBH",
	"Beccles Triathlon Club": "BECCT",
	"Beckenham Running Club": "BECK",
	"Bedford & County AC": "BEDC",
	"Bedford Harriers AC": "BEDH",
	"Bedfordshire County AA": "BEDSAAA",
	"Bedfordshire University": "BEDU",
	"Beeston AC": "BEEST",
	"Beith Harriers": "BEITH",
	"Belfast Association of Rockclimbers & Fellrunners": "BARF",
	"Belfast Olympians": "BELFO",
	"Belfast Royal Academy": "BELRA",
	"Belfast Running Club": "BELFR",
	"Belgrave Harriers": "BEL",
	"Bellahouston Harriers": "BELLA",
	"Bellahouston Road Runners": "BRR",
	"Belle Vue Racers": "BELLE",
	"Belper Harriers": "BELPH",
	"Benfleet RC": "BENRC",
	"Benson Striders": "BENSN",
	"Berkshire County AA": "BCAA",
	"Berriew Football Club": "BERFC",
	"Best Athletics": "BEST",
	"Betsi Runaways": "BETSI",
	"Beverley Athletic Club": "BEV",
	"Bexhill Runners & Triathletes": "BRT",
	"Bexley AC": "BEXLY",
	"Bicester AC": "BIC",
	"Bicester Triathlon Club": "BITRI",
	"Biddulph RC": "BIDDU",
	"Bideford AAC": "BIDEF",
	"Biggleswade Athletic Club": "BIG",
	"Billericay Striders": "BILLS",
	"Billingham Marsh Hse H & AC": "BMHH",
	"Bingley Harriers & AC": "BINGH",
	"Birchfield Harriers": "BIRCH",
	"Birkenhead AC": "BIRAC",
	"Birmingham Cross Country League": "BXL",
	"Birmingham Running Athletics & Triathlon Club": "BRAT",
	"Birmingham Swifts": "BIRSW",
	"Birstall RC": "BRC",
	"Birtley AC": "BIRTY",
	"Bishops Stortford RC": "BSTOR",
	"Bitton Road Runners": "BITTN",
	"Black Combe Runners": "BLACR",
	"Black Country Triathletes": "BLACT",
	"Black Girls Do Run UK": "BGDR",
	"Black Pear Joggers": "BPJ",
	"Blackburn Harriers & AC": "BBRNH",
	"Blackburn Road Runners": "BBRNR",
	"Blackheath & Bromley Harriers AC": "BB",
	"Blackhill Bounders": "BLACB",
	"Blackley North Manchester AC": "BNM",
	"Blackpool Wyre & Fylde AC": "BPOOL",
	"Blackwater Valley Runners": "BLKWV",
	"Blaenafon Joggers": "BLAEJ",
	"Blaenau Gwent Athletics": "BLAE",
	"Blaydon & Elswick": "BLAYE",
	"Blaydon Harriers & AC": "BLAYH",
	"Blood, Sweat & Tears": "BST",
	"Blyth Running Club": "BLYTH",
	"Blythe Bridge RC": "BLYBR",
	"BMAF Services Limited": "BMAFS",
	"Boalloy Running Club": "BOA",
	"Bodmin Dragons Triathlon Club": "BDTC",
	"BodyFit Cumbria Running Club": "BODYF",
	"Bodyworks XTC Tri Store": "BODYX",
	"Bognor & Chichester AC": "BOGCH",
	"Bognor Regis Tone Zone Runners": "BOGRT",
	"Bolt Running Club": "BOLT",
	"Bolton United Harriers & AC": "BOLTU",
	"Border Harriers & AC": "BORDH",
	"BornReady Academy": "BORN",
	"Borrowdale Fell Runners": "BDFR",
	"Boston & District AC": "BOSTD",
	"Bourne Town Harriers": "BTOWN",
	"Bournemouth AC": "BOURN",
	"Bournemouth Joggers": "BOJOG",
	"Bournville Harriers": "BORNV",
	"Bourton Roadrunners Club": "BOURR",
	"Bovey Valley Runners": "BOVVR",
	"Bowland Fell Runners": "BOWFR",
	"Boxted Runners": "BOXTD",
	"Brackla Harriers": "BRCLA",
	"Brackley and District RC": "BRACD",
	"Bracknell AC": "BRACK",
	"Bracknell Bounders": "BRKB",
	"Bracknell Forest Runners": "BRCKF",
	"Bracknell Road Runners": "BRCRR",
	"Bradford Airedale AC": "BRADA",
	"Bradford, Keighley & Skipton Disability Athletics (BKS)": "BKSDA",
	"Braintree & District AC": "BRAIN",
	"Bramhall Runners": "BRAMH",
	"Bramley Breezers": "BRAMB",
	"Brecon Athletic Club": "BRECA",
	"Brecon Multisport Club": "BRECM",
	"Brecon Triathlon Club": "BRECT",
	"Brentwood Beagles Athletics Club": "BRBEA",
	"Brentwood Running Club": "BWRC",
	"Bridgend Athletics": "BRIDE",
	"Bridgend Runners": "BRIDR",
	"Bridgnorth AC": "BRIDG",
	"Bridgnorth Running Club": "BRIRC",
	"Bridgwater & District Road & Trail Runners": "BDRTR",
	"Bridlington Road Runners": "BRID",
	"Brighton & Hove AC": "BRIHC",
	"Brighton Phoenix": "BRIPH",
	"Brighton Phoenix Tri": "BRIPT",
	"Brighton Triathlon Club": "BRITC",
	"Bristol and West AC": "BRIW",
	"Bristol University Athletics & Cross Country Club": "BRACC",
	"Bristol University Triathlon Club": "BRTRI",
	"British Airways AC": "BAW",
	"British Masters Athletic Federation": "BMAF",
	"British Milers Club": "BMC",
	"British Rowing": "BR",
	"British Universities and Colleges Sport": "BUCS",
	"British Wheelchair Athletics Association": "BWAA",
	"British Wrestling": "BW",
	"BRJ Run and Tri": "BRJ",
	"Bro Dysynni AC": "BRODY",
	"Bromley Veterans AC": "BROMV",
	"Bromsgrove and Redditch": "BROMR",
	"Broseley Joggers": "BROSJ",
	"Broxbourne Runners": "BROXR",
	"BTR Road Runners": "BTRRR",
	"Buckingham & Stowe RC": "BUST",
	"Buckinghamshire County AA": "BUCKSAA",
	"Buckinghamshire New University": "BUCKU",
	"Buckley RC": "BUCKL",
	"Bude Rats (Run and Tri)": "BUDER",
	"Builth and District Running Club": "BUILT",
	"Bungay Black Dog RC": "BBDRC",
	"Bure Valley Harriers": "BVH",
	"Burgess Hill Runners": "BURGH",
	"Burnden Road Runners": "BURNR",
	"Burnham Joggers": "BUR",
	"Burnham On Sea Harriers": "BOSH",
	"Burnley AC": "BURNA",
	"Burren AC": "BURRN",
	"Burton AC": "BURT",
	"Bury Athletic Club": "BURY",
	"Bushfield Joggers": "BUSHF",
	"Buxton AC": "BUXTA",
	"Bys Vyken Race Team": "BVRT",
	"C-Squad": "CSQD",
	"Cadence Tri": "CADNC",
	"Caerleon RC": "CAERR",
	"Caerphilly Runners": "CPRC",
	"Cairngorm Runners": "CAIGR",
	"Caistor Running Club": "CAIST",
	"Caithness Amateur Athletic Club": "CAITH",
	"Calder Valley Fell Runners": "CALVF",
	"Calderglen Harriers": "CGH",
	"Caldicot Running Club": "CALDI",
	"Calne Running Club": "CALNE",
	"Camberley & District AC": "CADAC",
	"Camberwell Runners": "CBWR",
	"Cambridge & Coleridge AC": "CAMCO",
	"Cambridge Harriers": "CAMBH",
	"Cambridge Runners": "CAMRU",
	"Cambridge Triathlon Club": "CAMBT",
	"Cambridge University AC": "CUAC",
	"Cambridge University Hare and Hounds Club": "CUHH",
	"Cambridge University Old Gits": "CUOG",
	"Cambridgeshire Athletic Association": "CAMBS",
	"Cambuslang Harriers": "CAMBL",
	"Campbeltown RC": "CMBLT",
	"Candour Track Club": "CNDR",
	"Candy Racing": "CANDY",
	"Cannock & Stafford AC": "CANST",
	"Canterbury Harriers": "CNTBH",
	"Cardiff Archers": "ARCHA",
	"Cardiff Athletics": "CARD",
	"Cardiff Cheetahs": "CARDC",
	"Cardiff Harlequins Running Club": "CDFHQ",
	"Cardiff Junior Tri Club": "CJTRI",
	"Cardiff Metropolitan University Athletics Club": "UCARM",
	"Cardiff Triathletes": "CARDT",
	"Cardiff University Athletics Club": "UCARD",
	"Cardigan RC": "CARDI",
	"Carlisle Aspatria AC": "CASPI",
	"Carmarthen Harriers": "CARMA",
	"Carmen Runners": "CARMR",
	"Carnegie Harriers": "CARNH",
	"Carnethy Hill Running Club": "CHRC",
	"Carryduff Running Club": "CARRY",
	"Castle Point Joggers": "CASPJ",
	"CDF Runners": "CDF",
	"Celtic Tri": "CELTR",
	"Central Athletic Club": "CENTR",
	"Central Lancs Running & Triathlon Club (CLAN)": "CLAN",
	"Central Park Athletics": "CENTP",
	"Centurion RC": "CENRC",
	"Cerist Triathlon Club": "CERIS",
	"Chard Road Runners": "CHARD",
	"Charnwood Athletic Club": "CHARN",
	"Chase Harriers": "CHASH",
	"Chatteris Running Club": "CHATT",
	"Cheadle RC": "CHEAD",
	"Cheddar RC": "CHEDR",
	"Chelmsford AC": "CHELM",
	"Cheltenham and County Harriers": "CHECH",
	"Chepstow Harriers": "CHEPH",
	"Cherwell Runners & Joggers": "CHERJ",
	"Cheshire County Athletics Association": "CCAA",
	"Cheshire Dragons": "DRAGC",
	"Chessington Unity Running Club": "CUR",
	"Chester Le Street & Dist AC": "CHLSD",
	"Chester Triathlon Club": "CHTRI",
	"Chesterfield & District AC": "CHFLD",
	"Chichester Runners & AC": "CHIRA",
	"Chiltern Harriers AC": "CHIL",
	"Chineham Park Running Club": "CHPRC",
	"Chippenham Harriers": "CHIPH",
	"Chirnside Chasers": "CHIRC",
	"Chorley Athletic and Triathlon Club": "CHRLY",
	"Chorlton Runners": "CHRLR",
	"Christchurch Runners": "CTCHR",
	"Cirencester AC": "CIREN",
	"City of Birmingham Striders": "COBS",
	"City of Derry Spartans": "COD",
	"City of Hull AC": "CHULL",
	"City of Lancaster Triathlon": "COLT",
	"City of Lisburn AC": "COLAC",
	"City Of Norwich AC": "CONAC",
	"City Of Plymouth AC": "CPLYM",
	"City of Portsmouth AC": "CPORT",
	"City Of Salisbury AC & RC": "CSALS",
	"City of Sheffield and Dearne AC": "CSHEF",
	"City of Southend On Sea AC": "STHEN",
	"City of Stoke AC": "STOKE",
	"City of York AC": "CYORK",
	"Civil Service": "CIVIL",
	"Clapham Chasers": "CC",
	"Clapham Pioneers": "CLP",
	"Claremont Road Runners": "CLMRR",
	"Claygate Recreation Ground Trust": "CRGT",
	"Clayton-le-Moors Harriers": "CLYMH",
	"CLC Striders": "CLCST",
	"Cleethorpes AC": "CLEET",
	"Cleethorpes Triathlon Club": "CLETC",
	"Cleobury Mortimer Running Club": "CLEOM",
	"Clevedon AC": "CLEVE",
	"Clonliffe Harriers": "CLONL",
	"Clonmel": "CLONM",
	"Clowne Road Runners Club": "CLOWN",
	"Club Pulse Runners": "CPLSE",
	"Clwb Rhedeg DVT Running Club": "CRDRC",
	"Clwb Rhedeg Pontardawe RC": "CRPRC",
	"Clwb Run Wales": "CLRWA",
	"Clwb Triathlon Llanelli": "LLANT",
	"Clwydian Range Runners": "CLWRR",
	"Clydesdale Harriers": "CLYDH",
	"County Antrim Harriers Co Antrim Harriers": "CANTH",
	"Coalfields Triathlon Club": "COALT",
	"Coalville Triathlon Club": "CTC",
	"Coastal Runners": "COAST",
	"Cobra Running & Triathlon Club": "COBRT",
	"Colchester & Tendring AC": "COLTE",
	"Colchester Harriers AC": "COLCH",
	"Collingwood AC": "COL",
	"Coltishall Jaguars RC": "COLTJ",
	"Colwyn Bay AC": "COLW",
	"Comets Road Running Club": "COMET",
	"Compton Harriers RC": "COMP",
	"Congleton Harriers": "CONGL",
	"Cookham Running Club": "COOK",
	"Cool Runnings UK": "COOLR",
	"Corby AC": "CORBY",
	"Cornelly Striders AC": "CSAC",
	"Cornish Rebels Athletic Club": "CREBL",
	"Cornwall Athletic Club": "CORNW",
	"Corsham Running Club": "CORSH",
	"Corstorphine AAC": "CORST",
	"Cosmic Hillbashers": "COSM",
	"Coventry Godiva Harriers": "COVG",
	"Coventry Triathletes": "COVTR",
	"Coventry University AC": "COVU",
	"Craigavon AC": "CRAIG",
	"Crawley AC": "CRAW",
	"Crawley Run Crew": "CRC",
	"Crawley Saints & Sinners Running Club": "CRSS",
	"Creazione Fitness Village Running Club": "CFVRC",
	"Crediton Running Network": "CRN",
	"Crewe and Nantwich AC": "CREWE",
	"Crewkerne RC": "CREWR",
	"Crickhowell Running Club": "CRRC",
	"Croft Ambrey RC": "CROFT",
	"Crook & Dist Sports AC": "CROOK",
	"Crossgar Harriers": "CROSH",
	"Crowborough Runners": "CROW",
	"Croydon Harriers": "CRO",
	"Croydon Running Sisters": "CRORS",
	"Crystal Palace Fun Runners": "CPFR",
	"Crystal Palace Triathletes": "CPALT",
	"CSR Running Club": "CSRRC",
	"Cumberland AC": "CUMBA",
	"Cumberland Fell Runners": "CUMFR",
	"Cumbernauld Amateur Athletics Club": "CUMBN",
	"Cumbria School of Hammer": "CUSH",
	"Cwmbran Harriers": "CWMB",
	"Cybele": "CYBEL",
	"Cybi Striders": "CYBI",
	"Dacorum Athletics Club": "DACT",
	"Dagenham 88 Runners": "DAG88",
	"Daiwa Capital Markets": "DAICM",
	"Dalbeattie Running Club": "DALBE",
	"Danum Harriers": "DANUM",
	"Dark Peak Fell Runners": "DPFR",
	"Darlington Harriers & Athletics Club": "DARLH",
	"Dartford Harriers AC": "DARTF",
	"Dartford Road Runners": "DART",
	"Dartmouth AAC": "DARTM",
	"Darwen Dashers RC": "DWNDR",
	"Datchet Dashers": "DATCH",
	"Daventry AAC": "DTRY",
	"Daventry Road Runners": "DAVRR",
	"Dawlish Coasters": "DAWCO",
	"Deal Tri Club": "DEAL",
	"Dee Runners": "DEER",
	"Deeside Amateur Athletic Club": "DEESA",
	"Deeside Runners": "DEESR",
	"Deestriders RC": "DEEST",
	"Defra AC": "DEFRA",
	"Delamere Spartans": "DSPART",
	"Denbigh Harriers": "DENBH",
	"Denbighshire Triathlon Club": "DENTC",
	"Denby Dale Athletics Club": "DENDA",
	"Denby Dale Travellers": "DENDT",
	"Dengie 100 Runners": "DENGI",
	"Denmead Striders": "DENMD",
	"Derby Athletic Club": "DERBY",
	"Derby Triathlon Club": "DERBT",
	"Derby University": "DERBU",
	"Dereham Runners & AC": "DEREH",
	"Derry Track Club": "DTC",
	"Derwent AC Cockermouth": "DERWC",
	"Derwent Runners": "DERWR",
	"Derwent Runners (Derby)": "DERWD",
	"Derwent Valley Running Club": "DERWV",
	"Derwent Valley Trail Runners": "DERWT",
	"Derwentside AC": "DERWS",
	"Desborough Runners": "DES",
	"Desford Striders": "DSFRD",
	"Deveron Harriers": "DEVH",
	"Devizes Running Club": "DEVZR",
	"Devon County Athletics Association": "DEVON",
	"Dewsbury Road Runners": "DEWS",
	"DH Runners": "DHRUN",
	"Diamond Runners": "DIAMR",
	"Didcot Runners": "DIDCT",
	"Didsbury Runners": "DIDSB",
	"DILI Academy": "DILI",
	"Diss and District AC": "DISSD",
	"DNA Green Team": "GREEN",
	"DNA Orange Team": "ORANG",
	"Dolly Mixtures": "DOLLY",
	"Doncaster Athletic Club": "DONCA",
	"Dooneen AC": "DOON",
	"Dorchester AC": "DORAC",
	"Dorchester RIOT": "DORIO",
	"Dorking & Mole Valley AC": "DMV",
	"Dorset County Athletics Association": "DCAA",
	"DORSET DODDLERS RC": "DORSD",
	"Doss AC": "DOSS",
	"Dover Road Runners AC": "DOVRR",
	"Down Triathlon Club": "DTRIC",
	"Dragons Running Club": "DRAGN",
	"Dragons Running Club (Aberdare)": "DRAGA",
	"Dragons Running Club (Leeds)": "DRAGL",
	"Dragons Running Club (Sale)": "DRAGS",
	"Droitwich AC": "DROIT",
	"Dromore Athletic Club": "DROM",
	"Dronfield RC": "DRONR",
	"DSW Para Athletics": "DSWPA",
	"Dub Running Club": "DUBR",
	"Dudley and Stourbridge Harriers": "DSH",
	"Dudley Kingswinford RC": "DKING",
	"Dulwich Park Runners": "DPR",
	"Dulwich Runners AC": "DUL",
	"Dumbarton AAC": "DUMB",
	"Dumfries Harriers": "DUMFH",
	"Dumfries Running Club": "DUMFR",
	"Dunbar Running Club": "DNBAR",
	"Dunblane Runners": "DUNB",
	"Dundee Hawkhill Harriers": "DUNDH",
	"Dundee Road Runners AC": "DRR",
	"Dundee University Athletics and Cross Country Club": "DUNDU",
	"Dunfermline Track and Field Club": "DTFC",
	"Dunleer AC": "DUNLR",
	"Duns Running Club": "DUNSR",
	"Dunstable RRC": "DUNST",
	"Durham City Harriers & AC": "DURHC",
	"Durham Fell Runners": "DURFR",
	"Durham University AC": "UDURH",
	"Dursley Running Club": "DURSL",
	"Dwain Chambers Sprint Club": "DCSC",
	"Ealing Eagles Running Club": "EALE",
	"Ealing Southall & Middlesex AC": "ESM",
	"Easingwold Running Club": "EASWO",
	"East Antrim Harriers AC East Antrim Harriers": "EANTM",
	"East Cheshire Harriers & Tameside AC": "ECHT",
	"East Coast AC": "ECOST",
	"East Cornwall Harriers": "ECORH",
	"East Down AC": "EDAC",
	"East End Road Runners": "EERR",
	"East Essex Triathlon Club": "EESTC",
	"East Grinstead & District AC": "EGD",
	"East Grinstead Runners": "EGDR",
	"East Grinstead Triathlon Club": "EGDTC",
	"East Hull Harriers": "EHHAC",
	"East Kilbride AC": "EKILB",
	"East London Runners": "ELR",
	"East Manchester Harriers": "EMANH",
	"East Sutherland AC": "ESUTH",
	"East Wales": "EWAL",
	"Eastbourne Rovers AC": "EASTR",
	"Eastern Masters AC": "EMAC",
	"Eastleigh RC": "ELEIG",
	"Ebbw Vale RC": "EBBWV",
	"Eccleshill Road Runners": "ECCLS",
	"Eden Runners": "EDENR",
	"Edge Hill University": "EDGEH",
	"Edinburgh Athletic Club": "EDIN",
	"Edinburgh Eagles Disability Athletics Club": "EEDAC",
	"Edinburgh Napier University": "NAPIU",
	"Edinburgh Running Network": "EDINN",
	"Edinburgh University AC": "UEDIN",
	"Edinburgh University Hare & Hounds": "EUNIH",
	"Edmonton RC": "EDMON",
	"Egdon Heath Harriers": "EGDON",
	"Eglinton Road Runners": "EGRR",
	"Elgin Amateur Athletics Club": "ELGN",
	"Ellesmere Port RC": "ELLEP",
	"Ellon Amateur Athletics Club": "ELLON",
	"Elmbridge RRC": "ELM",
	"Elswick Harriers": "ELSWH",
	"Elvet Striders": "ELVET",
	"Ely Runners": "ELYR",
	"Emerald AC": "EMER",
	"Emersons Green Running Club": "EGRC",
	"Emlyn Runners": "EMLRU",
	"Emsworth Joggers": "EMSWJ",
	"Enfield and Haringey AC": "ENFH",
	"England Athletics": "EA",
	"England Masters Athletics Association": "EMAA",
	"England Masters Team": "EMAAT",
	"England Midlands": "ENGM",
	"England North": "ENGN",
	"England South": "ENGS",
	"Ennis Track AC": "ENNIS",
	"Enniskillen Running Club": "ENNIK",
	"Epsom & Ewell Harriers": "EE",
	"Epsom Allsorts": "EAL",
	"Epsom Oddballs RC": "EPO",
	"Erewash Valley RC": "EREWV",
	"Erimus AC": "ERIM",
	"Erme Valley Harriers": "ERMEV",
	"Eryri Harriers": "ERYRI",
	"Essex County Athletic Association": "ECAA",
	"Essex University": "ESSXU",
	"Essington Harriers Running Club": "EHRC",
	"Eton Manor AC": "ETONM",
	"Evenwood Road Runners": "EVENW",
	"Evesham Vale Running Club": "EVRC",
	"Exeter College Running Club": "EXETC",
	"Exeter Harriers": "EXETH",
	"Exeter TC": "EXETT",
	"Exeter University Athletic Club": "UEXET",
	"Exmouth Harriers": "EXMH",
	"Exmouth Running Belles": "EXMRB",
	"Eye Community Runners": "EYECR",
	"Eynsham Road Runners": "EYNRR",
	"Fairlands Valley Spartans": "FVS",
	"Fairwater Runners Cwmbran": "FAIR",
	"Falkirk Victoria Harriers": "FALKV",
	"Falkland Trail Runners": "FALKT",
	"Falmouth RRC": "FRRC",
	"Fareham Crusaders Running Club": "FHMC",
	"Farnborough Flyers": "FLYERS",
	"Farnham Common Joggers & Wheelers Sports Club (JAWS)": "JAWS",
	"Farnham Runners": "FARNR",
	"Farnham Town Running Club": "FHMTR",
	"Farnham Triathlon Club": "FARNT",
	"Farsley Flyers": "FAFLY",
	"Fast Twitch Athletics Club": "FTAC",
	"Faversham Running Club": "FAVRC",
	"Federation of Disability Sport Wales": "FDSW",
	"Felixstowe Road Runners": "FELIX",
	"Fenland Running Club": "FENRC",
	"Fermanagh Orienteering Club": "FRMGH",
	"Ferranti AAC": "FAAC",
	"Ferrybank AC": "FERRY",
	"Fetch Everyone": "FETCH",
	"Fife AC": "FIFE",
	"Finch Coasters": "FINCH",
	"Fingallians": "FING",
	"Fitmums and Friends": "FITMM",
	"Fittleworth Flyers": "FIT",
	"Fleckney & Kibworth Athletics Club": "FKRC",
	"Fleet & Crookham AC": "FLEET",
	"Fleet Street Runners": "FSR",
	"Flying Machines Running Club": "FLYRC",
	"Folkestone RC": "FOLKR",
	"Fordy Runs Running Club": "FORDY",
	"Forest Monsters": "FORSM",
	"Forest of Dean AC": "FODAC",
	"Forfar Road Runners": "FORFR",
	"Formula One Circuit Crew": "F1CC",
	"Forres Harriers": "FORRE",
	"Forth Valley Flyers": "FORVF",
	"Foyle Valley AC": "FOYLE",
	"Framlingham Flyers": "FRAMF",
	"Fraserburgh Running Club": "FRAS",
	"Freedom Tri": "FRTRI",
	"Friday Night Under the Lights/ Ben Noad Coaching": "FNUL",
	"Friends and Runners": "FANDR",
	"Frome Running Club": "FROME",
	"FT Nikkei": "FTNIK",
	"Ful-On Tri Club": "FOT",
	"Fulham Running Club": "FRC",
	"Full Potential": "FULPT",
	"FWF Run": "FWFR",
	"Fylde Coast Runners": "FYLCR",
	"Fylde Tri Club": "FYLTC",
	"Gade Valley Harriers": "GADE",
	"Gainsborough & Morton Striders": "GAINS",
	"Gala Harriers Athletic Club": "GAHA",
	"Galbally Runners": "GALBL",
	"Garden City Runners": "GDNCY",
	"Garioch Road Runners": "GARR",
	"Garscube Harriers": "GARS",
	"Garstang Running Club": "GARSR",
	"Gateshead Harriers & AC": "GATES",
	"Gator Athletics Club": "GATOR",
	"Giffnock North AC": "GIFFN",
	"Gillingham Trotters": "GTROT",
	"Girvan Athletic Club": "GIRVH",
	"Glasgow Caledonian University Athletics Club": "GCUAC",
	"Glasgow City AC": "GLASC",
	"Glasgow FrontRunners": "GFRNT",
	"Glasgow Jaguars Track and Field Club": "GJTF",
	"Glasgow Pole Vault School": "GPVS",
	"Glasgow School of Sport": "GSOS",
	"Glasgow University AC": "UGLAS",
	"Glasgow University Hares and Hounds": "GUNIH",
	"Glaxo Hoad Hill Harriers": "GLAX",
	"Glenlough Running Club": "GLENL",
	"Glens Runners": "GLENS",
	"Glossopdale Harriers": "GLOSS",
	"Gloucester AC": "GLOS",
	"Gloucestershire University": "UGLOC",
	"Glynneath AC": "GLYNN",
	"Gmax TrackStars AC": "GTS",
	"Gnosall Globetrotters Running Club": "GNOSG",
	"Go Be Runners": "GOBER",
	"GOG Triathlon Club": "GOGTC",
	"Goldsmiths University AC": "GOLDU",
	"GoodGym Race Team": "GGRT",
	"Goole Viking Striders": "GOOVS",
	"Goole Youth AC": "GOOLE",
	"Goring RRC": "GORRR",
	"Gosforth Harriers & AC": "GOSFH",
	"Got To Tri": "GOTRI",
	"Goyt Valley Striders": "GOYT",
	"Grange Farm & Dunmow Runners": "GFDR",
	"Grantham AC": "GRNTA",
	"Grantham Running Club": "GRHM",
	"Grassroots To Greatness": "G2G",
	"Gravesend Road Runners": "GRARR",
	"Great Bentley Running Club": "GBBC",
	"Great Milton Athletics Club": "GMILT",
	"Great Western Runners": "GWR",
	"Great Yarmouth & District AC": "GYARD",
	"Great Yarmouth Road Runners": "GYRR",
	"Greenock Glenpark Harriers": "GGLEN",
	"Greenwich Tritons Triathlon Club": "GTTC",
	"Griffithstown Harriers": "GRIFF",
	"Grimsby Harriers & AC": "GRIMH",
	"Grimsby TC": "GRIMT",
	"Grove Lane": "GLANE",
	"Guernsey AC": "GUERN",
	"Guernsey TC": "GTC",
	"Guest": "GUEST",
	"Guildford & Godalming AC": "GG",
	"Guildford Young Athletes Club": "GYAC",
	"Gwent Police Running Section": "GWENP",
	"GymTech Health & Fitness Running Club": "GTHF",
	"Haddington Running Club": "HADD",
	"Hadleigh Hares AC": "HADHR",
	"Hailsham Harriers": "HAILH",
	"Halesowen Athletics & Cycling Club": "HALES",
	"Halewood Apollo Athletics Club": "HLWA",
	"Halifax Harriers & AC": "HLFXH",
	"Hallamshire Harriers Sheffield": "HALLH",
	"Halmer Harriers": "HALMR",
	"Halstead RRC": "HRRC",
	"Halterworth Harriers": "HALTW",
	"Halton & Frodsham Harriers": "HFRH",
	"Hambleton Athletics & Running Club": "HARC",
	"Hamilton and District AC": "HDAC",
	"Hamilton Harriers": "HAMH",
	"Hamwic Harriers Running Club": "HWH",
	"Hamworthy Harriers": "HAMWH",
	"Handsworth Roadhogs": "HWRH",
	"Handy Cross Runners": "HXR",
	"Harborough AC": "HARB",
	"Hardley Runners": "HARDL",
	"Haringey AC": "HARNG",
	"Haringey, Hackney and Islington Athletics Club": "HHIAC",
	"Harlow AC": "HARLO",
	"Harlow RC": "HARRC",
	"Harmeny Athletic Club": "HARM",
	"Harold Wood Running Club": "HAROLD",
	"Harpenden Arrows": "HARPA",
	"Harrogate Harriers & AC": "HARRH",
	"Harrogate Tri Club": "HARRT",
	"Harrow AC": "HARR",
	"Hart Road Runners": "HARTR",
	"Hartlepool Athletics Club": "HARTA",
	"Hartlepool Burn Road Harriers": "HARTH",
	"Harvard & Yale University Team": "HYUNI",
	"Harvel Hash House Harriers": "H4",
	"Harwell Harriers": "HARWH",
	"Harwich Runners": "HRWCH",
	"Haslemere Border AC": "HASB",
	"Hastings AC": "HASTA",
	"Hastings Runners": "HRU",
	"Hatch Warren Runners": "HWR",
	"Hatton Darts": "HATTD",
	"Havant Athletic Club": "HAVAN",
	"Haverhill Running Club": "HAVHL",
	"Havering AC": "HAVE",
	"Hawkinge Hurricanes Running Club": "HHRC",
	"Hayle Runners": "HAYLE",
	"Haywards Heath Harriers": "HAYHH",
	"Hazlemere Runners": "HAZLR",
	"Headington RR": "HEAD",
	"Heanor Running Club": "HEANR",
	"Heath Massive Run Club": "HEMRC",
	"Heathfield RRC": "HEA",
	"Heaton Harriers & AC": "HTONH",
	"Hedge End Running Club": "HERC",
	"Helensburgh AAC": "HELEN",
	"Helm Hill Runners": "HELM",
	"Helpston Harriers AC": "HELPH",
	"Helsby Running Club": "HELSB",
	"Henfield Joggers": "HEN",
	"Hengoed Harriers": "HENGH",
	"Henley Harriers": "HENLEYH",
	"Henley Rowing Club": "HENLY",
	"Hercules Wimbledon AC": "HW",
	"Hereford & County AC": "HERCO",
	"Hereford Couriers": "HEREC",
	"Heriot-Watt University Athletics Club": "HWUH",
	"Hermitage Harriers": "HERMH",
	"Herne Hill Harriers": "HHH",
	"Hertfordshire County Amateur Athletic Association": "HERTS",
	"Herts Phoenix AC": "HERPH",
	"Heyford Aardvarks Running Club": "HEYFA",
	"High Wycombe Cycling Club": "HWYCC",
	"Higham Harriers": "HIGHM",
	"Highgate Harriers": "HIGH",
	"Highland Hill Runners": "HHR",
	"Highway 10K": "H10K",
	"Highworth Running Club": "HIGHW",
	"Hillingdon AC": "HILL",
	"Hillingdon Triathletes": "HILLT",
	"Hillsborough & Rivelin Running Club": "HILLS",
	"Hinckley Running Club": "HINCK",
	"HLB Runners": "HLB",
	"HMG Japan Desk": "HMGJD",
	"Hockley Trail Runners": "HTR",
	"Hogweed Trotters": "HOGWT",
	"Holcombe Harriers": "HOLCH",
	"Holland Sports AC": "HOL",
	"Holme Pierrepont RC": "HPP",
	"Holmfirth Harriers AC": "HOLMF",
	"Honiton RC": "HONRC",
	"Hook Norton Harriers": "HOOK",
	"Horley Harriers Running Club": "HOR",
	"Hornchurch Athletics": "HORN",
	"Horsforth Harriers": "HORSH",
	"Horsham Blue Star Harriers": "HBS",
	"Horsham Joggers": "HOJ",
	"Horwich R M I Harriers": "HORWI",
	"Houghton Harriers & AC": "HHAAC",
	"Hove Hornets": "HOVEH",
	"Howfen Runners": "HOWFR",
	"Howgill Harriers": "HOWGH",
	"Huddersfield Univesity": "UHUDD",
	"Hull Springhead Harriers": "HULLH",
	"Hull University AC": "HULLU",
	"Huncote Harriers": "HUNH",
	"Hungerford Hares RC": "HHARE",
	"Hunters Bog Trotters": "HBT",
	"Huntingdonshire AC": "HUNTA",
	"Hunwick Harriers": "HUNWH",
	"HY Athletics Club": "HYAC",
	"Hyde Park Harriers": "HPH",
	"Hyde Village Striders": "HYDEV",
	"Hydrographic Harriers": "HYDRO",
	"ICL AC": "ICLAC",
	"Idle AC": "IDLEA",
	"Ilford AC": "ILFRD",
	"Ilfracombe Running Club": "ILFRA",
	"Ilkeston Running Club": "ILKES",
	"Ilkley Harriers AC": "ILKH",
	"Impact Athletic Club": "IMPCT",
	"Imperial College Cross Country & AC": "UICL",
	"Imperial College Hockey Club": "ICHC",
	"Imperial College Medics": "UICLM",
	"Imperial College TC": "ICTC",
	"Imperial Triathlon Club": "ICTRI",
	"Independent Intelligent Fitness": "IIF",
	"Indian Masters Team": "XXIND",
	"Insch Trail Running Club": "INSCH",
	"Inspire Runners Chichester": "IRCH",
	"International Island Games Association": "IIGA",
	"Inverclyde Athletic Club": "INVCL",
	"Inverness Harriers AAC": "INVNH",
	"Invicta East Kent AC": "INVIC",
	"Invictus Games Foundation": "IAM",
	"Ipswich Harriers": "IPSWH",
	"Ipswich Jaffa RC": "IPSWJ",
	"Ipswich Phoenix Running Club": "IPSWP",
	"Ireland Masters": "IMAT",
	"Irish Masters Team": "XXIRL",
	"Irvine RC": "IRVIN",
	"Island TC": "ISTC",
	"Isle Of Man Veterans AC": "IOMVA",
	"Isle Of Wight AC": "IOW",
	"Isle Of Wight RR AC": "IOWRR",
	"Isle of Wight Triathlon Club": "IOWT",
	"Islwyn Running Club": "ISLRC",
	"Istead & Ifield Harriers": "IIH",
	"Italy Masters Team": "XXITA",
	"Itchen Spitfires Running Club": "ITCH",
	"Ivanhoe Robins Junior Athletics Club": "IVHRO",
	"Ivanhoe Runners": "IVNHR",
	"Iveragh AC": "IVERA",
	"Japanese Masters Team": "XXJPN",
	"Jarrow & Hebburn AC": "JARRH",
	"Jelly Legs Running Club": "JLEGS",
	"Jersey Spartan AC": "JERSP",
	"Jersey TC": "JERT",
	"Jesmond Joggers": "JJOG",
	"Jesus College Cross Country Club": "JCCCC",
	"JET Programme": "JETPR",
	"Jog Lisburn Running Club": "JLISB",
	"Jog Moira": "JOGMO",
	"JP Morgan RC": "JPMOR",
	"JSK Running Club": "JSK",
	"Junior Triathlon Coaching": "JTRIC",
	"Jura AC": "JURA",
	"KC Runners": "KCRUN",
	"Keele University Athletics & Cross Country": "UKEEL",
	"Keighley & Craven AC": "KLYC",
	"Keith and District AAC": "KEITH",
	"Kendal Amateur Athletic Club": "KENDL",
	"Kenilworth Runners": "KENR",
	"Kent AC": "KEN",
	"Keswick AC": "KSWCK",
	"Kettering Town Harriers": "KTH",
	"Kidderminster and Stourport": "KIDDS",
	"Kidlington Running Club": "KIDRC",
	"Kilbarchan AAC": "KILBA",
	"Kildare AC": "KIL",
	"Kilkenny City Harriers": "KILK",
	"Killamarsh Kestrels": "KMKS",
	"Killeeshil Runners": "KILL",
	"Kilmarnock Harrier & Athletic Club": "KILMH",
	"Kimberley & District Striders": "KDS",
	"Kimberworth Striders": "KIMWS",
	"Kinawley Running Group": "KINAW",
	"Kingfisher Harriers": "KINGF",
	"Kings College London": "UKCL",
	"Kings Heath RC - The Lions": "KHRC",
	"Kingston AC and Poly Harriers": "KACPH",
	"Kingston University AC": "KUAC",
	"Kingston upon Hull AC": "KHULL",
	"Kingstone Runners Barnsley": "KRBAR",
	"Kinross Road Runners": "KINRR",
	"Kirkby Milers AC": "KKBYM",
	"Kirkintilloch Olympians": "KIRKO",
	"Knaresborough Striders": "KNARE",
	"Knavesmire Harriers": "KNAVE",
	"Knockmany Running Club": "KNCKY",
	"Knowle & Dorridge RC": "KNOWD",
	"Knowsley Harriers": "KNWHR",
	"Knutsford Harriers & Athletics Club": "KHAC",
	"Knutsford Tri Club": "KTRI",
	"Lagan Valley AC": "LAVAC",
	"Lakeside Lincoln Running Club": "LAKLI",
	"Lancashire Walking Club": "LANCW",
	"Lancaster & Morecambe Athletics Club": "LANCM",
	"Lancaster Runners": "LANCR",
	"Lancaster University Running & Athletics Club": "LUNI",
	"Lancing Eagles RC": "LAE",
	"Larkfield Athletics Club": "LARKF",
	"Larkhall YMCA Harriers": "LARKH",
	"Larne AC": "LARNE",
	"Lasswade Athletics Club": "LASSW",
	"Latvian Masters Team": "XXLAT",
	"Lauderdale Limpers Running Club": "LAULR",
	"Launceston AC": "LAUNA",
	"Launceston Road Runners": "LAUNR",
	"Lauriston Runners Club": "LRC",
	"Lavington Athletics": "LAV",
	"Law & District AAC": "LAWD",
	"Lawley Running Club": "LAWLR",
	"LDN Brunch Club": "LDNBC",
	"Le Cheile AC": "LCHEI",
	"Leamington Athletics Academy": "LAA",
	"Leamington Cycling and Athletic Club": "LEAM",
	"Ledbury & District Harriers": "LEDDH",
	"Leeds & Bradford Triathlon Club": "LBTRC",
	"Leeds Beckett": "LBECK",
	"Leeds City Athletic Club": "LEEDS",
	"Leeds Dock Running Club": "LDRC",
	"Leeds University AC and CC Club": "ULEED",
	"Leicester Coritanian AC": "LEICC",
	"Leicester Triathlon Club": "LTC",
	"Leicester Walking Club": "LEICW",
	"Leigh Harriers & AC": "LEIGH",
	"Leigh on Sea Striders": "LEISS",
	"Leighton Buzzard Athletic Club": "LBAC",
	"Leighton Buzzard Triathlon Club": "LBTC",
	"Leighton Fun Runners": "LFR",
	"Les Croupiers RC": "CROUP",
	"Leven Valley AC": "LEVEN",
	"Levenshulme Runners": "LEVRU",
	"Lewes AC": "LEWES",
	"Lichfield Running Club": "LICHR",
	"Lifford Strabane AC": "LIFFS",
	"Lincoln & District Runners": "LINCD",
	"Lincoln Wellington Athletic Club": "LINCW",
	"Lincs S&C RC": "LNCSC",
	"Lindley Running Club": "LNLRC",
	"Lingfield RC": "LNG",
	"Linlithgow Athletic Club": "LLGAC",
	"Liss Runners": "LISS",
	"Little Baddow Ridge Runners": "LBADR",
	"Littleborough Runners": "LITBR",
	"Littledown Harriers": "LITDH",
	"Liverpool Harriers & AC": "LIVER",
	"Liverpool John Moores University AC": "LJMU",
	"Liverpool Pembroke & Sefton H AC": "LIVPS",
	"Liverpool Running Bugs": "LPRB",
	"Liverpool University AC": "LIVU",
	"Livingston Athletic Club": "LIVAD",
	"Llamwyr Llyn Striders": "LLANM",
	"Llanelli AAC": "LLAN",
	"Llanelli Strollers": "LLANS",
	"Llangollen Running Club": "LLRC",
	"Lliswerry Runners": "LLIS",
	"Lochaber Athletic Club": "LOCH",
	"Loftus & Whitby AC": "LOFWA",
	"Lomond Hill Runners & AAC": "LOMO",
	"London City Runners": "LCR",
	"London Fields Triathlon Club": "LFTC",
	"London Frontrunners": "LFRON",
	"London Heathside": "LONH",
	"London School of Economics Athletics Club": "LSE",
	"London Unis and Colleges Athletics": "LUCA",
	"Lonely Goat RC": "LGOAT",
	"Long Eaton Running Club": "LERC",
	"Longstanton and Northstowe Limpers": "LONGS",
	"Longwood Harriers AC": "LWH",
	"Lordshill Road Runners": "LORDS",
	"Lothian Running Club": "LOTHR",
	"Loughborough Students AC": "ULOUG",
	"Loughborough Triathlon RC": "LTRC",
	"Loughborough University": "LOUGH",
	"Loughrea AC": "LGHAC",
	"Loughton AC": "LGHTN",
	"Loughview AC": "LGHVW",
	"Louth AC": "LOUTA",
	"Louth Triathlon Club": "LOUTT",
	"Low Fell RC": "LOWFL",
	"Lowestoft Road Runners": "LOWE",
	"Ludlow Runners": "LUDLR",
	"Ludlow TC": "LUDLT",
	"Luton Athletic Club": "LUTON",
	"Luton Lions Running Club": "LUTLR",
	"Lymm Runners": "LYMMR",
	"Lytchett Manor Striders": "LMS",
	"Lytham St Annes RR Club": "LYSTA",
	"Mablethorpe Running Club": "MBLR",
	"Maccabi London Harriers": "MLH",
	"Macclesfield Harriers & AC": "MACFH",
	"Magherafelt Harriers": "MAGH",
	"Maguiresbridge RC": "MAGUR",
	"Maiden Newton Runners": "MDNNR",
	"Maidenhead AC": "MDNHD",
	"Maidstone Harriers": "MHARR",
	"Maindy Harriers": "MAIND",
	"Maldwyn Harriers": "MALDW",
	"Mallusk Harriers": "MALSK",
	"Maltby Running Club": "MALT",
	"Malvern Buzzards Running Club": "MALVB",
	"Malvern Joggers": "MALVJ",
	"Manchester Frontrunners": "MFRON",
	"Manchester Harriers & AC": "MANCH",
	"Manchester Metropolitan University": "MMU",
	"Manchester Triathlon Club": "MANCT",
	"Manchester YMCA Harriers": "MYMCH",
	"Mansfield Harriers": "MANSH",
	"Mansfield Road Runners": "MANSR",
	"Manx Fell Runners": "MANXF",
	"Manx Harriers": "MANXH",
	"Manx Tri-Club": "MANXT",
	"March AC": "MARCH",
	"Market Drayton RC": "MKTDR",
	"Marlborough Athletics": "MARL",
	"Marlborough Running Club": "MARLR",
	"Marlow Striders": "MAR",
	"Marsden Racers": "MARSR",
	"Marsh Lane Harriers": "MLHAR",
	"Marshall Milton Keynes AC": "MMK",
	"Maryhill Harriers": "MARYH",
	"Massey Ferguson RC": "MFRC",
	"Matlock Athletic Club": "MATLK",
	"Maverick Run Project": "MVKRP",
	"McCarkiss Endurance Project": "MCKEP",
	"Meads Runners": "MEADS",
	"Med High Running Club": "MED",
	"Medway and Maidstone AC": "MEDM",
	"Medway Tri": "MDTRI",
	"Meirionnydd Running Club": "MEIRI",
	"Meltham AC": "MELTM",
	"Menai Track & Field": "MENA",
	"Mendip Athletic Club": "MEND",
	"Mendip Triathlon and Running Club": "MENDT",
	"Mercia Fell Runners": "MERFR",
	"Mere Runners": "MERER",
	"Mersey Tri": "MERST",
	"Merthyr Harriers RRC": "MERTH",
	"Merthyr Running Club": "MERTR",
	"Metro Aberdeen Running Club": "METAB",
	"Metropolitan Police AC": "METPA",
	"Metros RC": "METRC",
	"Micky Morris Racing Team": "MMRT",
	"Mid Argyll AC": "MIDAR",
	"Mid Essex Casuals": "MESXC",
	"Mid Sussex Triathlon Club": "MSTC",
	"Mid Ulster AC": "MULST",
	"Middlesbrough & Cleveland Harriers": "MCH",
	"Middlesbrough Athletic Club": "MIDLE",
	"Middlesex Amateur Athletic Association": "MIDDXAA",
	"Middlesex University AC": "MIDDU",
	"Middleton Harriers AC": "MDDLH",
	"Midhurst Milers": "MID",
	"Midland Masters AC": "MMAC",
	"Midland Masters Throwers Group": "MMTG",
	"Midlands Counties Athletics Association": "MCAA",
	"Milburn Harriers": "MILB",
	"Mile High": "MILEH",
	"Millfield School": "MILLS",
	"Millom Striders": "MILOM",
	"Milocarian AC": "MILOC",
	"Milton Keynes Distance Project": "MKDP",
	"Minehead RC": "MINHR",
	"Mizuno": "MIZUN",
	"Mojo Run Fit": "MOJO",
	"Momiji charity": "MOMJI",
	"Moneyglass and District Runners Moneyglass & District Runners": "MNYGS",
	"Monkstown Spartans AC": "MNKST",
	"Monross Trailblazers": "MONRT",
	"Montrose and District Athletics Club": "MDAC",
	"Moorfoot Runners": "MRFT",
	"Moorhaven RC": "MORHR",
	"Moray Road Runners": "MORAR",
	"Morley Running Club": "MORLY",
	"Mornington Chasers": "MORNC",
	"Moroccan Masters Team": "XXMAR",
	"Morpeth Harriers & AC": "MORP",
	"Mossley AFC Running Club": "MAFC",
	"Mossley Hill AC": "MOSAC",
	"Mote Runners": "MOTER",
	"Motherwell Athletics Club": "MOTHR",
	"Mounts Bay Harriers": "MBH",
	"Mourne Harriers": "MOURN",
	"Mourne Runners": "MOURR",
	"Mow Cop Runners": "MOWCR",
	"Murlough AC": "MRLGH",
	"Musselburgh and District AC": "MUSSD",
	"Mynydd Du Mountain Runners": "MYNYD",
	"Mynyddwyr De Cymru": "MYNDC",
	"Na Fianna Runners": "NAFIR",
	"Naas AC": "NAAS",
	"Nairn Area Amateur Athletic Club": "NAAAC",
	"Nairn Road Runners": "NRNRR",
	"Nantwich Running Club": "NANT",
	"Natural Born Runners": "NBR",
	"Neath Harriers": "NEATH",
	"NEJ Running Club": "NEJP",
	"Nene Valley Harriers": "NENE",
	"Netherhall AC": "NETHL",
	"New Balance TC": "NBAL",
	"New Eltham Joggers": "NEJ",
	"New England Distance Club": "NEDC",
	"New Forest Junior AC": "NFJ",
	"New Forest Runners": "NEWFR",
	"New Levels Run Club": "NLRC",
	"New Marske Harriers Club": "NMH",
	"New Zealand Masters Team": "XXNZL",
	"Newark AC": "NWRKA",
	"Newark Striders Running Club": "NWRKS",
	"Newbridge AC": "NEWAC",
	"Newburgh Dunes Running Club": "NEWDU",
	"Newburn Running Club": "NEWBR",
	"Newbury AC": "NEWB",
	"Newcastle and District AC": "NEWCD",
	"Newcastle (Staffs) Tri Club": "NEWTC",
	"Newcastle Angels": "NEWCA",
	"Newcastle Frontrunners": "NEWCF",
	"Newcastle Staffs AC": "NSTAF",
	"Newcastle University AC": "UNEWC",
	"Newcastle University Triathlon Club": "NUTRI",
	"Newent Runners": "NEWNT",
	"Newham & Essex Beagles AC": "NEB",
	"Newmarket Cycling & Triathlon Club": "NEWMC",
	"Newmarket Joggers": "NEWMJ",
	"Newport and District RC": "NADRC",
	"Newport Harriers": "NEWPH",
	"Newquay & Par AC": "NQP",
	"Newquay Road Runners": "NEWQR",
	"Newry Athletic Club Newry AC": "NEWRY",
	"Newry City Runners AC": "NEWCR",
	"Newton Abbot AC": "NEWAB",
	"Newton Road Runners": "NEWRR",
	"NICSAC NI Civil Service AC": "NICS",
	"NI Mountain Running Association": "NIMRA",
	"NI Technical Officials Association": "NITOA",
	"NI Ultra Running Association": "NIURA",
	"Nidd Valley Road Runners": "NIDDV",
	"Nikko Asset Management": "NIKAM",
	"Nithsdale AC": "NITH",
	"NMP Hearts": "NMP",
	"Norfolk Gazelles AC": "NORFG",
	"Norham Running Club": "NORHM",
	"North Ayrshire AC": "NAYR",
	"North Belfast Harriers": "NBH",
	"North Cotswold Tri & Run": "NCTR",
	"North Derbyshire RC": "NDERB",
	"North Devon AC": "NORDV",
	"North Devon RRC": "NDRR",
	"North Down AC": "NDAC",
	"North East Masters AA": "NEMAA",
	"North East Project": "NEP",
	"North East Veterans AC": "NEVAC",
	"North Fermanagh Fitness Club": "NFFC",
	"North Herts Road Runners": "NHERT",
	"North Highland Harriers": "NHH",
	"North Leeds Fell Runners": "NLFR",
	"North Norfolk Beach Runners": "NNKBR",
	"North Norfolk Harriers Athletics Club": "NNHAC",
	"North Shields Polytechnic Club": "NSHH",
	"North Somerset AC": "NSOME",
	"North Uist Amateur Athletics Club": "NUIST",
	"North Wales": "NWAL",
	"North Wales Road Runners": "NWRRC",
	"North York Moors AC": "NYM",
	"North Yorkshire Police AC": "NYPAC",
	"Northampton AC": "NPTON",
	"Northampton Road Runners": "NORRR",
	"Northants Tri": "NRHTC",
	"Northbrook Athletic Club": "NOBRK",
	"Northern (Isle of Man) Athletic Club": "IOMN",
	"Northern Constabulary Sports & AC": "NCPS",
	"Northern Fells Running Club": "NFELL",
	"Northern Ireland Masters Athletic Association": "NIMAA",
	"Northern Masters AC": "NMAC",
	"Northumberland Fell Runners": "NORFR",
	"Northumbria University": "NRTHU",
	"Northwich Running Club": "NWICH",
	"Norwich Road Runners": "NRR",
	"Notfast RC": "NTFST",
	"Nottingham Trent University AC": "NTU",
	"Nottingham Trent University Triathlon Club": "NTTRI",
	"Nottingham University Old Boys": "NOBS",
	"Notts Athletic Club": "NOTTS",
	"Notts Women Runners": "NOTTW",
	"Nuclear Races Striders": "NUCRS",
	"Nuneaton Harriers": "NUNH",
	"Ochil Hill Runners": "OCHHR",
	"Off that couch fitness": "OTCF",
	"Ogmore Phoenix Runners": "OGMRE",
	"Okehampton Running Club": "OKEHR",
	"Oldham & Royton H & AC": "OLD",
	"Olney Runners": "OLN",
	"Olympia Triathlon club": "OTC",
	"Olympian Youth & Athletic Club": "OLYYA",
	"Omagh Harriers": "OMAGH",
	"Omagh Triathlon Club": "OMTRI",
	"OMG AC": "OMG",
	"On the Run Aylesbury": "RAYLE",
	"One Track": "ONE",
	"Optima Racing Team": "OPTRT",
	"Orangegrove AC": "ORANA",
	"Orchard County Runners": "ORCHD",
	"Orion & Ilford": "ORILF",
	"Orion Harriers": "ORION",
	"Orkney Athletic & Running Club": "OARC",
	"Ormeau Runners": "ORM",
	"Orpington Road Runners": "ORR",
	"Ossy Joggers": "OSJOG",
	"Oswestry Olympians": "OSOL",
	"Oswestry Olympians Athletics and Triathlon Club": "OSWES",
	"Otley AC": "OTLEY",
	"Outdoor Fitness": "ODFC",
	"Overton Harriers & AC": "OVERH",
	"Owls AC": "OWLS",
	"Oxford & Cambridge University Team": "OCUNI",
	"Oxford Brookes Running & AC": "OXBRO",
	"Oxford City AC": "OXFC",
	"Oxford Tri": "OXTRI",
	"Oxford University Athletic Club": "OUAC",
	"Oxford University Cross Country Club Old Members": "OUCCCOM",
	"Oxford University Cross-Country Club": "OUCCC",
	"Oxford University Old Gits": "OUOG",
	"Oxfordshire Athletic Association": "OXON",
	"Oxted Runners": "OXTED",
	"PACE Running Club": "PCERC",
	"Pacemaker": "PACE",
	"Paddock Wood AC": "PADW",
	"Parasport NI": "PARNI",
	"Parc Bryn Bach Running Club": "PBBR",
	"Paul Popham Running Club": "PPRC",
	"Paxcroft Road Runners": "PAXCR",
	"PB Running Club": "PBR",
	"Peel Road Runners": "PEELR",
	"Pegasus AC": "PEGAC",
	"Pegasus Running Club": "PEGRC",
	"Pembrokeshire Harriers": "PEMB",
	"Penarth and Dinas Runners": "PENDI",
	"Pencoed Panthers": "PENCD",
	"Pencoed TC": "PENCT",
	"Pendle Athletic Club": "PENDL",
	"Penicuik Harriers": "PENIH",
	"Penistone Footpath Runners & Athletic Club": "PENFR",
	"Penn & Cornell University Team": "PCUNI",
	"Penny Lane Striders": "PENNY",
	"Pensby Runners": "PENSB",
	"Penyffordd Run Club": "PENRC",
	"Perth Road Runners": "PRR",
	"Perth Strathtay Harriers": "PSH",
	"Peterborough & Nene Valley AC": "PNVAC",
	"Peterborough AC": "PBORO",
	"Peterhead Athletics Club": "PTERH",
	"Petts Wood Runners": "PETWR",
	"Pewsey Vale RC": "PEWV",
	"PH Racing Club": "PHRC",
	"Phoenix Flyers AC": "PFAC",
	"Pitreavie AAC": "PITRE",
	"Pitsea RC": "PITSR",
	"Planet Earth Games": "PEG",
	"Plymouth Falconers": "PLYMF",
	"Plymouth Harriers": "PLYMH",
	"Plymouth Musketeers Running Club": "PLMUS",
	"Plymouth Triathlon Club": "PLYMT",
	"Plymouth University": "UPAC",
	"Plymstock Road Runners": "PLYMR",
	"Pocklington Runners": "POCKR",
	"Polegate Plodders": "PGP",
	"Police Service of Northern Ireland AC": "PSNI",
	"Police Sport UK": "PSUK",
	"Polish Masters Team": "XXPOL",
	"Pont-Y-Pwl & District Runners": "PONP",
	"Pontefract AC": "PAC",
	"Ponteland Runners": "PONTR",
	"Pontyclun Athletics Club": "PONT",
	"Pontyclun Road Runners": "PONRR",
	"Pontypridd Roadents AC": "PONTY",
	"Poole AC": "POOLE",
	"Poole Runners": "POOLR",
	"Poplar Running Club": "POPRC",
	"Port Talbot Harriers": "PTH",
	"Portadown Running Club": "PORT",
	"Porthcawl Runners": "PORTC",
	"Portishead R C": "PORHD",
	"Portobello Running Club": "PRTB",
	"Portslade Hedgehoppers": "PSHH",
	"Portsmouth Joggers": "PORTJ",
	"Portsmouth Triathletes": "PORTT",
	"Prestatyn RC": "PRTYN",
	"Presteigne Pacers": "PRTGP",
	"Preston Harriers": "PREST",
	"Prestwich AC": "PRSTW",
	"Pudsey & Bramley AC": "PUDSE",
	"Pudsey Pacers RC": "PUDRC",
	"Purbeck Runners": "PURBR",
	"Purple Patch Runners": "PPR",
	"Pyeroy Hamilton Harriers AC": "PHAMH",
	"QBE Running Club": "QBE",
	"Quakers Running Club": "QUAKE",
	"Quays Running Club": "QUAYS",
	"Queen Mary & Westfield College Athletics & Cross Country": "QMWC",
	"Queens AC": "QEENH",
	"Queens TC": "QEENT",
	"Queens University AC": "QUBAC",
	"Queensbury Running Club": "QRC",
	"Race Hub": "RACEH",
	"Race Rapid": "RRAPD",
	"Race Walking Association": "RWA",
	"Radcliffe AC": "RADCL",
	"Radley Athletic Club": "RAD",
	"Radley College Harriers": "RCH",
	"RAF Athletics": "RAF",
	"Ramsey Road Runners": "RAMSR",
	"Ranelagh Harriers": "RAN",
	"Rasharkin Runners": "RASHK",
	"Ravens City of London Running Club": "RCLRC",
	"Ravens School Runners": "RAVEN",
	"Rawmarsh Runners": "RAWMR",
	"RBR Club": "RBRC",
	"Reach Running Club": "REACH",
	"Reading AC": "READ",
	"Reading Joggers": "REDJ",
	"Reading Rascals": "REDRS",
	"Reading Roadrunners": "READR",
	"Rebel Runners Medway": "REBEL",
	"Red Kite Runners": "RKITE",
	"Red Rose Road Runners": "RRRR",
	"Red Star AC": "REDST",
	"Redcar Race Walking Club": "REDCW",
	"Redcar Running Club": "REDCR",
	"Redditch Stars": "REDD",
	"Redhill & Surrey Beagles AC": "REDSB",
	"Redhill Road Runners": "RDHRR",
	"Redway Runners": "REDW",
	"Reepham Runners": "REEPR",
	"Refail Runners": "REFAI",
	"Regent House": "RGNT",
	"Regis Road Runners": "REGIS",
	"Reigate Priory AC": "REI",
	"Retford AC": "RETAC",
	"Rhayader AC": "RHAY",
	"Rhayader RC": "RHAYA",
	"Rhedwyr Hebog Runners": "RHEDW",
	"Rhondda AAC": "RHONA",
	"Rhondda Valley Runners": "RVR",
	"Rhymney Valley AC": "RHYM",
	"Ribble Valley Harriers": "RIBVH",
	"Richmond & Zetland Harriers": "RZH",
	"Richmond Running Club": "RICHM",
	"Ripley Running Club": "RIPLR",
	"Ripon Roar": "RIPRO",
	"Ripon Runners": "RIPRU",
	"Rise Running Club": "RISE",
	"Rising Brook Runners": "RBRRU",
	"Riversway Road Runners": "RIVER",
	"Road Runners Club": "RRC",
	"Roadhoggs Leicester AC": "RHLAC",
	"RoadRunners AC": "RRAC",
	"Rochdale Harriers & AC": "ROCHH",
	"Rock Runners": "ROCKR",
	"Rock Salt Runners": "ROCKS",
	"Rode and Norton Striders": "RODNS",
	"Rodillian Runners": "RODIL",
	"Roehampton University": "RHU",
	"Rolls Royce Harriers": "RRH",
	"Romanian Masters Team": "XXROU",
	"Romsey Road Runners": "RRR",
	"Ross County Athletics Club": "RCAC",
	"Rossendale Harriers & AC": "ROSSN",
	"Rotary Road Runners": "ROTRR",
	"Rotherham Harriers and AC": "ROTHE",
	"Rotherham Running Club": "RTHRC",
	"Rothwell Harriers & AC": "ROTH",
	"Roundhay Runners": "ROUND",
	"Royal Air Force Medical Services": "RAFMS",
	"Royal Holloway University of London AC": "ROHOL",
	"Royal Mail Run GMC": "RMRUN",
	"Royal Manor Of Portland AC": "RMPAC",
	"Royal Navy Athletics Club": "RNAVY",
	"Royal Navy Triathlon Club": "RNTRI",
	"Royal Sutton Coldfield Athletics Club": "RSC",
	"Royal Wootton Bassett Hounds RC": "RWBH",
	"Royston Runners": "ROYST",
	"Royton Road Runners": "ROYTR",
	"RTW Runners": "RTW",
	"Rugby & Northampton AC": "RUNOR",
	"Rugby Football League": "RFL",
	"Rugby Football Union": "RFU",
	"Rugeley Runners": "RUGE",
	"Ruislip RC": "RUISL",
	"Run & Ride Athletics Club": "RANDR",
	"Run 4 U and Perform Running Club": "RUPRC",
	"Run Academy Worthing": "RAW",
	"Run Alcester": "RNALC",
	"Run Bitch Run": "RBR",
	"Run Brum Crew": "RBRUM",
	"Run Dem Crew": "RDC",
	"Run Fast": "RUNFT",
	"Run for Enda": "ENDA",
	"Run Free Fell Runners": "RFFR",
	"Run Livingston": "RLIV",
	"Run Middlewich": "RUNMW",
	"Run Mummy Run Ltd": "RUNMR",
	"Run Namaste Eat": "RUNNE",
	"Run Nation Running Club": "RNRC",
	"Run Newport": "RUNNP",
	"Run Sandymoor": "RUNSM",
	"Run Things Run Club": "RTRC",
	"Run-Anon": "RANON",
	"Run4all Neath Running Club": "R4ALL",
	"Runhead AC": "RUNHD",
	"Runners-Next-the-Sea": "RNTS",
	"Running Bear": "RUNBR",
	"Running For 14846": "RUN14",
	"Running for Time": "R4T",
	"Running Forever RC": "RFRC",
	"Running Head First": "RUNHF",
	"Running Jo Club": "RUNJO",
	"Running Somewhere Else": "RUNSE",
	"Running With Matt": "RWMTT",
	"Runnymede Runners": "RMD",
	"RunThrough": "RUNT",
	"RunThrough North": "RUNTN",
	"RunWednesdays": "RUNWS",
	"Rushcliffe AC": "RUSHC",
	"Rushmere Community Runners": "RUSCR",
	"Rutland Running & Triathlon Club": "RUTRT",
	"RVC Tri Club": "RVC",
	"Ryde Harriers": "RYDEH",
	"Ryston Runners": "RYSTR",
	"S Factor Academy": "SFACT",
	"Saddleworth Runners Club": "SWRC",
	"Saffron Athletics Club": "SAFFA",
	"Saffron Striders RC": "SAFFS",
	"Saint Edmund Pacers": "STEDP",
	"Saintfield Striders": "SAINT",
	"Sale Harriers Manchester": "SALEH",
	"Salford Harriers & AC": "SALFH",
	"Salford Metropolitan AC": "SALFM",
	"Saltaire Striders": "SALTS",
	"Saltwell Harriers": "SALTH",
	"San Domenico RC": "SANDO",
	"Sandbach Striders": "SNDBC",
	"Sandhurst Joggers": "SHJ",
	"Sarn Helen": "SARN",
	"Sarnia Walking Club": "SARNW",
	"Sawtry Walk to Run": "SAWRW",
	"Saxmundham Sports Running & Fitness Club": "SAXMS",
	"Scarborough Athletic Club": "SCARB",
	"Scotia Race Walking Club": "SCOWC",
	"Scottish Athletics Ltd": "SA",
	"Scottish Athletics Unattached Athlete": "SAUA",
	"Scottish Dental Runners": "SDENT",
	"Scottish Disability Sport": "SDS",
	"Scottish Fire & Rescue AC": "SCOFR",
	"Scottish Prison Service AAC": "SPRIS",
	"Scottish Veteran Harriers Club": "SVHC",
	"Scrabo Striders Running Club Scrabo Striders": "SCRAB",
	"Scunthorpe & District AC": "SCTPD",
	"SCVAC Veterans League": "SCVL",
	"Seaford Striders RC": "SEAFD",
	"Seafront Shufflers": "SEAFS",
	"Seapark Athletics Club Seapark AC": "SEAAC",
	"Seaton Athletic Club": "SEATN",
	"Sedbergh School Running Club": "SEDBG",
	"Sedgefield Harriers": "SEDGH",
	"Sedgley Striders": "SEDGL",
	"Selby Striders": "SELBY",
	"Serpentine RC": "SERP",
	"Settle Harriers": "SETLH",
	"Sevenoaks AC": "SEVOK",
	"Severn AC": "SEVRN",
	"SHAEF Shifters Running Club": "SHAEF",
	"Shaftesbury Barnet Harriers": "SBH",
	"Shamrock Running Club": "SHAMR",
	"Sheen Shufflers": "SHESH",
	"Sheffield Hallam University Athletics Club": "SHEFH",
	"Sheffield RC": "SHFR",
	"Sheffield Triathlon Club": "SHEFT",
	"Shefford Runners": "SHEFR",
	"Shelton Striders": "SHELT",
	"Shenley Striders": "SHENS",
	"Shepshed Running Club": "SHEPS",
	"Sherfield Park Runners": "SHERF",
	"Shetland AAC": "SHETL",
	"Shettleston Harriers": "SHETT",
	"Shildon Running & AC": "SHILD",
	"Shrewsbury AC": "SHRSB",
	"Shropshire Shufflers": "SHSH",
	"Sidmouth Running Club": "SIDMR",
	"Silson AC": "SIL",
	"Silverdale RC": "SILVD",
	"Sinfin Running Club": "SNFIN",
	"Sip Running Club": "SIPRC",
	"Sittingbourne Striders": "SITBS",
	"Skegness & District Running Club": "SKEGD",
	"Skelmersdale Boundary Harriers": "SKELM",
	"Ski Club Nordic Highland": "SKHIG",
	"Skipton AC": "SKIPT",
	"Skye & Lochalsh Running Club": "SKYE",
	"Skyrac Athletic Club": "SKYRA",
	"Sleaford Striders Athletic Club": "SLEAF",
	"Sleaford Town Runners": "SLEAT",
	"SLGR": "SLGR",
	"Slieve Gullion Runners": "SGULL",
	"Slinn Allstars": "SLINN",
	"Slough Junior AC": "SJAC",
	"Slovakian Masters Team": "XXSVK",
	"Smalley Road Runners": "SMARR",
	"Sneyd Striders": "SNEYD",
	"Snowsport Scotland": "SNSCO",
	"Soar X Try": "SOARX",
	"SOAR6": "SOAR6",
	"SOAS Running Club": "SOAS",
	"Solent Running Sisters": "SRS",
	"Solihull & Small Heath Athletic Club": "SOLSH",
	"Solihull Triathlon Club": "SOLTC",
	"Somer Athletic Club": "SOMER",
	"Sospan Road Runners": "SOSPN",
	"South Birmingham Striders": "SBSR",
	"South Cheshire Harriers": "SCHES",
	"South Derbyshire Road Runners": "SDRR",
	"South Devon AC": "SDEV",
	"South Glos AC": "SGLOC",
	"South Kent Harriers": "SKH",
	"South Leeds Lakers Running Club": "SLLRC",
	"South London Harriers": "SLH",
	"South London Orienteers": "SLONO",
	"South Molton Strugglers": "SOMOS",
	"South of England Track and Field AC": "SETAF",
	"South Shields Harriers & AC": "SSHH",
	"South Uist and Eriskay Amateur Athletics Club": "SUIST",
	"South Wales": "SWAL",
	"South West Athletics Club": "SWAC",
	"South West Road Runners": "SWRR",
	"South West Veterans AC": "SWVAC",
	"South Yorkshire County Athletics Association": "SYCAA",
	"Southampton Athletic Club": "SOTON",
	"Southampton Solent University": "SOLNT",
	"Southampton Triathlon Club": "SOTNT",
	"Southampton University Athletics & Cross Country Club": "USOUT",
	"Southern (Isle of Man) AC": "IOMS",
	"Southern Counties Veterans AC": "SCVAC",
	"Southport Strollers": "SPS",
	"Southport Waterloo AC": "SPWAT",
	"Southville Running Club": "STHVL",
	"Southwark Athletics Club": "SACL",
	"Spa Striders": "SPAST",
	"Sparkhill Harriers": "SPARK",
	"Spectrum Striders": "SPECS",
	"SDP Track Club Speed Development Project Track Club": "SDPTC",
	"Spenborough & Dist AC": "SPENB",
	"Sperrin Harriers": "SPRN",
	"Spey Runners": "SPEYR",
	"Sphinx AC": "SPHNX",
	"Spirit of Monmouth": "SPMON",
	"Sporting Events UK": "SEUK",
	"Springburn Harriers": "SPRBH",
	"Springfield Striders RC": "SPRNG",
	"Springwell Running Club": "SPRGW",
	"Sri Chinmoy AC (Scotland)": "SRICH",
	"SS Athletics": "SSATH",
	"SS Athletics/Enfield & Haringey": "SSEH",
	"St Albans AC": "STAL",
	"St Albans Striders": "STALS",
	"St Annes Athletics Club": "STANN",
	"St Austell Athletes Running Club": "STAAR",
	"St Austell Running Club": "STARC",
	"St Helens Striders": "STRID",
	"St Helens Sutton AC": "STHEL",
	"St Michaels College AC": "STMIC",
	"St Neots Riverside Runners": "NEOTS",
	"Stadium Runners": "STADR",
	"Stafford Harriers": "STAFH",
	"Stafford Triathlon Club": "STRIC",
	"Staffordshire County Athletic Association": "STAFFCAA",
	"Staffs Moorlands AC": "STAFM",
	"Stainland Lions Running Club": "STAIL",
	"Stamford Striders": "STAMS",
	"Staple Hill Runners": "SHR",
	"Start2Jog": "S2J",
	"Steel City Striders Running Club": "STEEL",
	"Stevenage & North Herts AC": "SNH",
	"Stewartry Athletics Club": "STWT",
	"Steyning AC": "STY",
	"Sticker AFC Running Club": "STICK",
	"Still Waters Run Deep": "SWRD",
	"Stilton Striders": "STILT",
	"Stirling Triathlon Club": "STRI",
	"Stirling University Athletics Club": "STIRU",
	"Stock Exchange AC": "SEAC",
	"Stockport Harriers & AC": "STOCH",
	"Stockport Track & Field": "STKTF",
	"Stockport Tri Club": "STKTC",
	"Stocksfield Striders": "SFSDR",
	"Stockton Striders AC": "STKTN",
	"Stone Master Marathoners": "STNMM",
	"Stonehaven RC": "STHRC",
	"Stonehenge Striders": "STONE",
	"Stopsley Striders": "STOP",
	"Storm Plymouth": "SPLYM",
	"Stornoway Running & Athletics Club": "SRAC",
	"Stourbridge RC": "STRC",
	"Stowmarket Striders RC": "STOWM",
	"Stratford Upon Avon AC": "STRAT",
	"Strathaven Striders": "STRST",
	"Strathclyde Police AC": "STRAP",
	"Strathclyde University Harriers": "USTRA",
	"Strathearn Harriers": "STRTH",
	"Straw Bear Striders": "SBS",
	"Street Striders": "STSTR",
	"Stride Running Club": "STRIR",
	"Strideout Aston": "SOUTA",
	"Striders Of Croydon": "SOC",
	"Strive Racing Club": "STRVR",
	"Stroud & District AC": "STROU",
	"Stroud Mums on the Run": "SMOTR",
	"Stubbington Green Runners": "STUBG",
	"Sudbury Court Running Club": "SUDBC",
	"Sudbury Joggers": "SBJOG",
	"Sunderland Harriers & AC": "SUNDH",
	"Sunderland Strollers": "SUNDS",
	"Sunderland University": "SUNDU",
	"Surrey County Athletic Association": "SCAA",
	"Surrey Walking Club": "SWALK",
	"Sussex County Athletic Association": "SXCAA",
	"Sussex University": "USUSS",
	"Sutton & District AC": "SD",
	"Sutton in Ashfield Harriers & AC": "SAH",
	"Sutton Runners": "SUR",
	"Sutton Striders": "SUST",
	"Swale Combined AC": "SWALE",
	"Swaledale Runners": "SWADA",
	"Swanley & District AC": "SDAC",
	"Swansea Harriers": "SWAN",
	"Swansea University Athletics Club": "USWAN",
	"Swansea University Triathlon Club": "SSTRI",
	"Swansea Vale Tri": "SWAVT",
	"Swindon Harriers": "SWINH",
	"Swindon Stragglers": "SWING",
	"Swindon Striders": "SWINS",
	"Swindon Tri": "SWTRI",
	"Swinton Running Club": "SWINT",
	"Synergy RC": "SYN",
	"T3 Tadcaster Triathlon Team": "T3TC",
	"Tadcaster Harriers": "TADH",
	"Tadworth AC": "TAD",
	"Taf Running & Orienteering Team": "TROTS",
	"Tafelta AC": "TFLTA",
	"Tamar Trotters": "TAMAR",
	"Tamworth AC": "TAMW",
	"Tattenhall Runners": "THALL",
	"Taunton AC": "TAUNT",
	"Tavistock AC": "TAVSK",
	"Tavistock Run Project": "TAVRP",
	"Team Anstey Amblers and Runners": "ANSTY",
	"Team Balancise RC": "TBALR",
	"Team Bath Athletic Club": "TBATH",
	"Team Borders": "TBORD",
	"Team Coco": "COCO",
	"Team Derby Runner": "TDR",
	"Team Devizes – Moonrakers Athletics Club": "TDMAC",
	"Team Dorset Athletics Network": "TDAN",
	"Team Dunerunner": "DUNER",
	"Team East Haddon": "TEHAD",
	"Team East Lothian AC": "TEL",
	"Team Hounslow Athletic Club": "HOUNS",
	"Team Isle of Man": "TIOM",
	"Team Kennet Triathlon & AC": "TKTRI",
	"Team Marathon Road": "TMR",
	"Team Paris Marathon": "PARIM",
	"Team Synergy": "TSYN",
	"TeamSpy": "TSPY",
	"Teesdale AC": "TEESD",
	"Teignbridge Trotters": "TBT",
	"Telford AC": "TELFA",
	"Telford Harriers": "TELFH",
	"Templeogue AC": "TEMPL",
	"Termoneeny Running Club": "TRMNY",
	"Teviotdale Harriers": "TEVDL",
	"Tewkesbury Running Club": "TEWKS",
	"Thame Runners": "THAMR",
	"Thames Hare & Hounds": "THH",
	"Thames Turbo Triathlon": "TURBO",
	"Thames Valley Harriers": "TVH",
	"Thames Valley Triathletes": "TVTRI",
	"Thamesmead Running Club": "TMRC",
	"Thanet AC": "THANA",
	"Thanet Roadrunners AC": "THANR",
	"The Charging Bulls": "CGBL",
	"The Cowley Club": "COWC",
	"The Dearne ALC": "DEARN",
	"The Emmetts Running Club": "EMMTS",
	"The Gunn Show": "TGS",
	"The HAWCS": "HAWCS",
	"The Running Hub": "HUB",
	"The Sports Consultancy": "SPCON",
	"The Stragglers Running Club": "STR",
	"The Yellow Army": "TYA",
	"Thetford AC": "THET",
	"Thirsk & Sowerby Harriers": "TKSH",
	"Thornbury RC": "THORR",
	"Thorney RC": "THORN",
	"Thornton Cleveleys Running Club": "TCLYR",
	"Three Counties Running Club": "TCRC",
	"Three Witches Running Club": "TWITR",
	"Thurrock Harriers": "THURH",
	"Tidworth & Bulford AC": "TIDBU",
	"Tipton Harriers": "TIPTH",
	"Tiptree Road Runners": "TIPTR",
	"Tiverton Harriers": "TIV",
	"Todmorden Harriers": "TODMH",
	"Tonbridge AC": "TONB",
	"Tonbridge TC": "TONTC",
	"Torbay AAC": "TORB",
	"Torbay Tri Club": "TTRIC",
	"Torfaen Runners": "TORF",
	"Torque Racing Club": "TORQ",
	"Torrington AAC": "TORR",
	"Totley AC": "TOTLY",
	"Totton RC": "TOTTR",
	"Track Academy": "TACAD",
	"Track EAST": "TRACKE",
	"Trafford Athletic Club": "TRAFF",
	"Trail Running Association": "TRAIL",
	"Trail Tuesday Ripponden": "TTUER",
	"Trawden Athletic Club": "TRAWD",
	"Trent Park Running Club": "TRNTP",
	"Trentham RC": "TRENT",
	"Tri Hard Harriers": "TRIHH",
	"Tri London": "TRILO",
	"Tri Surrey Triathlon Club": "TRI",
	"Tri Tempo Eastbourne": "TRITE",
	"Tri-Anglia Triathlon Club": "TRANG",
	"Tri-Base Track & Field": "TRIBS",
	"Triathlon Inverness": "INVTC",
	"Tring RC": "TRING",
	"Troon Tortoises Athletics Club": "TROON",
	"Truro Running Club": "TRURO",
	"TS Harriers": "TSH",
	"Tuff Fitty Triathlon Club": "TFT",
	"Tunbridge Wells Harriers": "TUNW",
	"Turriff Running Club": "TURIF",
	"Tweed Leader Jed Track": "TLJT",
	"Tweed Striders": "TWEED",
	"Twemlow Track Club": "TREMT",
	"Tyler Inn": "TYLER",
	"Tyne Bridge Harriers": "TYNEB",
	"Tynedale Harriers & AC": "TYNED",
	"Uckfield Runners": "UCK",
	"UCL Athletics & Cross Country Club": "UCLAC",
	"UFFO Athletic Satellite Clubs": "UFFO",
	"UKnetrunner.co.UK": "UKN",
	"UKRunChat Running Club": "RCHAT",
	"Ulster University AC": "UULST",
	"Ultimate Plodders": "UPLOD",
	"Unattached": "UNATT",
	"Union of Brunel Students": "UBRUN",
	"United Kingdom Athletics": "UKA",
	"University College Birmingham": "UBIRMC",
	"University of Bath Athletics Club": "UBATH",
	"University of Bath Triathlon Club": "UBTRI",
	"University of Birmingham AC and Cross Country Club": "BUAC",
	"University of Birmingham Triathlon Club": "BUTRI",
	"University of Cambridge Triathlon Club": "CUTRI",
	"University of Central Lancashire AC": "UCLAN",
	"University of Chester": "UCHEST",
	"University of East Anglia AC": "UEANG",
	"University of East Anglia Triathlon Club": "UEATR",
	"University of East London": "UEL",
	"University of Exeter Triathlon Club": "UXTRI",
	"University of Glasgow Triathlon Club": "GUTRI",
	"University of Greenwich Athletics and Running Club": "UGREN",
	"University of Kent AC": "UKAC",
	"University of Law": "ULAW",
	"University of Leicester Running & Athletics Club": "UOLRA",
	"University of Lincoln Athletics & Cross Country Club": "ULINC",
	"University of London Athletics XC & Triathlon": "ULON",
	"University of Manchester Ath & XC Club": "UMANC",
	"University of Nottingham AC": "UNOTT",
	"University of Nottingham Triathlon Club": "UNTRI",
	"University of Oxford Triathlon Club": "OUTRI",
	"University of Portsmouth Athletics Club": "UPORT",
	"University of Reading AC": "UREAD",
	"University of Sheffield Orienteering & Fell Running Club": "SHUOC",
	"University of Sheffield Union of Students": "USHEF",
	"University of St Andrews Athletics and Cross Country Club": "STAND",
	"University of Surrey AC": "USURR",
	"University of Surrey Triathlon Club": "SUTRI",
	"University of Teesside": "UTEES",
	"University of the West of England ACCC": "UWEAC",
	"University of Warwick": "UWARW",
	"University of Westminster": "UWEST",
	"University of Winchester": "UWINC",
	"University of Worcester": "UWORC",
	"University of York Athletics Club": "UYORK",
	"University Wales - Aberystwyth": "UNIWA",
	"Unknown Runner": "UKNR",
	"Unsanctioned Athletics Racing Collective": "UARC",
	"Usk Runners": "USK",
	"UTS Running Club": "UTSRC",
	"Vale Of Aylesbury AC": "VOA",
	"Vale of York Athletic Community": "VOYAC",
	"Vale Royal AC": "VALER",
	"Valley Striders AC": "VASTR",
	"Vectis Academy Race Team": "VEC",
	"Vector Racing": "VECTR",
	"Vegan Runners UK": "VEG",
	"VeloRunner": "VELOR",
	"Verco Joggers": "VER",
	"Verwood Runners": "VWOOD",
	"Veterans AC": "VAC",
	"Viceroys Triathlon Club": "VTC",
	"Victoria Park and Connswater AC Victoria Park & Connswater": "VPCW",
	"Victoria Park City of Glasgow AC": "VPCOG",
	"Victoria Park Harriers and Tower Hamlets AC": "VPTH",
	"Victory AC": "VICAC",
	"Village Vipers": "VIVIP",
	"VocaLink Mastercard Running Club": "VLKMR",
	"Wadhurst Runners": "WAD",
	"Wakefield District H & AC": "WAKE",
	"Walden Track and Field": "WTF",
	"Walden Tri": "WALDT",
	"Wallasey Athletic Club": "WALLA",
	"Wallsend Harriers & AC": "WALLS",
	"Walney Wind Cheetahs": "WWC",
	"Walsall Arboretum Running Club": "WALAR",
	"Walton AC": "WALT",
	"Ward Park Runners": "WPR",
	"Ware Joggers": "WAJOG",
	"Wargrave & Twyford Runners": "WARGR",
	"Warley Woods Pacers": "WWOOD",
	"Warrington Athletic Club": "WARRA",
	"Warrington Road Runners": "WARRR",
	"Warrington Running Club": "WRTN",
	"Warriors Pentathlon and Athletic Club": "WPAAC",
	"Washington Running Club": "WASHR",
	"Watford Harriers": "WATFH",
	"Watford Joggers": "WATFJ",
	"Waveney Valley AC": "WAVVA",
	"Waverley Athletics Club": "WAVAC",
	"Waverley Harriers": "WAVEH",
	"Weald Tri Club": "WEALD",
	"Wearside Triathlon Club": "WEART",
	"WNR Wednesday Night Runners": "WEDSR",
	"Wee County Harriers": "WEECH",
	"Weir Archer Academy": "WEIRA",
	"Wellesley Runners": "WELLR",
	"Wellingborough & District AC": "WELBD",
	"Wellington College Club": "WCOLL",
	"Wells City Harriers": "WELCH",
	"Welsh Anglo Athletes": "WANGL",
	"Welsh Athletics Ltd": "WA",
	"Welsh Masters Athletics Limited": "WMAL",
	"Welsh Schools And Universities": "WSAU",
	"Wembley Pioneers": "WEMBP",
	"Wenlock Olympians": "WENOL",
	"Werrington Joggers": "WERRJ",
	"Wesham Road Runners & AC": "WESHM",
	"Wessex Road Runners": "WESRR",
	"West 4 Harriers": "W4H",
	"West Belfast Coolers": "WBCLR",
	"West Bromwich Harriers": "WBROM",
	"West Cheshire Athletic Club": "WCHES",
	"West Dunbartonshire Athletics Club": "WDUNB",
	"West End Road Runners": "WERR",
	"West End Runners": "WESTE",
	"West Hull Ladies": "WHULL",
	"West London Track and Field": "WLTF",
	"West Midlands Police": "WMP",
	"West Norfolk AC": "WNORF",
	"West Suffolk AC": "WSUFF",
	"West Wales": "WWAL",
	"West Wales Regional Athletics Council": "WWRAC",
	"West Wight Road Runners": "WWRR",
	"Westbourne R C": "WBRC",
	"Westbury Harriers": "WESTH",
	"Westerlands Cross Country Club": "WSTR",
	"Western Athletic Club (Isle of Man)": "IOMW",
	"Western Tempo": "WESTT",
	"Westminster Current Pupils": "WESTC",
	"Weston Athletic Club": "WAC",
	"Weston Whippets": "WWHIP",
	"Wetherby Runners AC": "WTHBY",
	"Weymouth St Pauls Harriers": "WSPH",
	"Wharfedale Harriers": "WDH",
	"Whitby Running Club": "WHITB",
	"Whitchurch Running Club": "WHITR",
	"Whitchurch Triathlon Club": "WHITT",
	"Whitchurch Whippets": "WHITW",
	"White Cliffs Athletics & Running Club": "WCARC",
	"White Horse Harriers AC": "WHH",
	"White Rock Runners": "WROCK",
	"Whitemoss Amateur Athletic Club": "WHITM",
	"Widnes Running Club": "WIDNS",
	"Wigan & District H & AC": "WIGAN",
	"Wigan Phoenix": "WPHNX",
	"Wight Tri": "WIGHT",
	"Wigston Phoenix RC": "WGSTN",
	"Wild Trail Runners": "WTR",
	"Willesden Triathlon Club": "WTC",
	"Willowfield Temperance Harriers Willowfield Harriers": "WILLH",
	"Wilmslow Running Club": "WILMR",
	"Wimbledon Windmilers": "WW",
	"Wimborne AC": "WIMBO",
	"Winchester & District AC": "WADAC",
	"Winchester Fit Club RC": "WADFR",
	"Winchester Running Club": "WINRC",
	"Windle Valley Runners": "WVR",
	"Windrush Triathlon Club": "WIN",
	"Windsor Slough Eton & Hounslow AC": "WSEH",
	"Windsor TC": "WINDT",
	"Wingerworth Wobblers": "WWWOB",
	"Winston Runners": "WINST",
	"Wirral AC": "WIRRL",
	"Wirral Vikings Racing Team": "WIRRT",
	"Witham RC": "WITHM",
	"Witham Runners (Lincolnshire)": "WITHR",
	"Witney Road Runners": "WITRR",
	"Woking Athletic Club": "WOK",
	"Wolds Veteran Runners Club": "WOLDV",
	"Wolverhampton & Bilston": "WOLVB",
	"Women on the Run": "WORUN",
	"Women Running Penarth": "WRPEN",
	"Woodbridge Shufflers RC": "WOODS",
	"Woodford Green Athletics Club with Essex Ladies": "WGEL",
	"Woodstock Harriers AC": "WOODH",
	"Wootton Road Runners": "WOOTT",
	"Worcester AC": "WORC",
	"Worksop Harriers": "WORKS",
	"Worthing & District Harriers": "WORDH",
	"Worthing Running Sisters": "WORRS",
	"Worthing Striders": "WORS",
	"Wreake & Soar Valley": "WREAK",
	"Wreake Runners": "WRE",
	"Wrecsam Tri": "WRECT",
	"Wrekin College Triathlon Club": "WCOLT",
	"Wrekin Harriers": "WRH",
	"Wrekin Road Runners": "WREK",
	"Wrexham Amateur Athletic Club": "WREX",
	"Wrexham Glyndwr University Athletics Club": "WGUAC",
	"www Runners": "WWW",
	"Wycombe Phoenix Harriers & AC": "WPH",
	"Wye Valley Runners": "WYEVR",
	"Wymondham AC": "WYMH",
	"Yate & District AC": "YATED",
	"Yate & Sodbury Striders": "YASS",
	"Yaxley Runners & Joggers": "YAXRJ",
	"Yeovil Olympiads AC": "YEOVO",
	"Yeovil Town RRC": "YEOVL",
	"York Acorn Running Club": "YACOR",
	"York Knavesmire Harriers": "YKH",
	"York St John University": "UYKSJ",
	"Yorkshire Wolds Runners": "YWR",
	"Young Athletes Club": "YAC",
	"Ystrad Mynach Running Club": "YMRC",
	"YU Life": "YULI",
	"Zoom Tri Club Bournemouth": "ZMTRI",
}
