// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseDirectory():Promise<string>;

export function EnterFullScreen():Promise<void>;

export function ExitFullScreen():Promise<void>;

export function GetAllLIFData():Promise<Array<main.LifData>>;

export function GetDisplayState():Promise<main.DisplayState>;

export function GetWebInterfaceInfo():Promise<string>;

export function SetCurrentLIF(arg1:main.LifData):Promise<void>;

export function SetDisplayState(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetRotationMode(arg1:string):Promise<void>;
