// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseDirectory():Promise<string>;

export function EnterFullScreen():Promise<void>;

export function ExitFullScreen():Promise<void>;

export function GetAllLIFData():Promise<Array<main.LifData>>;

export function GetWebInterfaceInfo():Promise<string>;
