// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDirectory() {
  return window['go']['main']['App']['ChooseDirectory']();
}

export function EnterFullScreen() {
  return window['go']['main']['App']['EnterFullScreen']();
}

export function ExitFullScreen() {
  return window['go']['main']['App']['ExitFullScreen']();
}

export function GetAllLIFData() {
  return window['go']['main']['App']['GetAllLIFData']();
}

export function GetDisplayState() {
  return window['go']['main']['App']['GetDisplayState']();
}

export function GetWebInterfaceInfo() {
  return window['go']['main']['App']['GetWebInterfaceInfo']();
}

export function SaveGraphic(arg1, arg2) {
  return window['go']['main']['App']['SaveGraphic'](arg1, arg2);
}

export function SetCurrentLIF(arg1) {
  return window['go']['main']['App']['SetCurrentLIF'](arg1);
}

export function SetDisplayState(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetDisplayState'](arg1, arg2, arg3);
}

export function SetLayoutTheme(arg1) {
  return window['go']['main']['App']['SetLayoutTheme'](arg1);
}

export function SetRotationMode(arg1) {
  return window['go']['main']['App']['SetRotationMode'](arg1);
}

export function SetShowBib(arg1) {
  return window['go']['main']['App']['SetShowBib'](arg1);
}
