// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDirectory() {
  return window['go']['main']['App']['ChooseDirectory']();
}

export function EnterFullScreen() {
  return window['go']['main']['App']['EnterFullScreen']();
}

export function ExitFullScreen() {
  return window['go']['main']['App']['ExitFullScreen']();
}

export function GetAllLIFData() {
  return window['go']['main']['App']['GetAllLIFData']();
}

export function GetWebInterfaceInfo() {
  return window['go']['main']['App']['GetWebInterfaceInfo']();
}
